/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package facade;

public class App {
    public static void main(String[] args) {
        wallet myWallet = new wallet();
    }
}

