/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package facade;

public class wallet {

    private credit myCreditCard;
    private debit myDebitCard = new debit(0);
    private cash myCash = new cash(0);

    public wallet(double credit, double debit, double cash) {

        this.myCreditCard = new credit(credit);
        this.myDebitCard = new debit(debit);
        this.myCash = new cash(cash);

        this.checkBalance();
        System.out.println("Wallet created");
    }

    void checkBalance() {
        System.out.println("credit: " + this.myCreditCard.getBalance()
                        + "\ndebit: " + this.myDebitCard.getBalance()
                        + "\ncash: " + this.myCash.getBalance());
    }
}

